### ISSUE TITLE
Toasts don't reorder when one of the toasts has been updated

### ISSUE THREAD

**Issue by Nyloth9** [ardeora/solid-toast#101]
When updating manually a toast with providing a new toast body with `toast(newBody, {id: id)`, if the new body has bigger height that the original, the rest of the toasts don't update and don't accomodate for the new height, so the updated toast gets cut off partially.

**Comment by Nyloth9** [comment]
Nvm

**Comment by pw-64** [comment]
How did you solve this issue?

I'm having the same problem where the below causes the longer message to overlap other notifications

```ts
  toast.success("first toast")
  const id = toast.loading("second toast");
  setTimeout(() => toast.success("test ".repeat(40), { id }), 500);
```

https://github.com/user-attachments/assets/7e036b31-44c3-4b19-9bee-4ea2da50e2be

**Comment by pw-64** [comment]
I fixed this with custom css, for anyone else with the same issue:

```tsx
<Toaster containerClassName="toaster" />
```

```css
.toaster {
  display: flex;
  flex-direction: column;
  gap: 8px;

  .sldt-active {
    position: relative !important;
    margin-top: 0 !important;
  }
}
```

https://github.com/user-attachments/assets/2823a2d6-ee73-4335-ac2f-46f372c1fa96
